#!/bin/sh
# Keywave deploy helper: generates a .env (TURN secret + public IP) so the
# bundled TURN relay and optional HTTPS work without hand-editing anything.
set -eu

ENV_FILE=".env"
if [ -f "$ENV_FILE" ]; then
  echo "$ENV_FILE already exists. Edit it directly, or remove it to regenerate."
  exit 0
fi

# --- strong shared TURN secret (used by both the app and coturn) -------------
if command -v openssl >/dev/null 2>&1; then
  SECRET=$(openssl rand -hex 32)
else
  SECRET=$(head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n')
fi

# --- best-effort public IP detection -----------------------------------------
IP=""
for u in https://api.ipify.org https://ifconfig.me https://icanhazip.com; do
  IP=$(curl -fsS -m 5 "$u" 2>/dev/null | tr -d '[:space:]') || IP=""
  [ -n "$IP" ] && break
done
echo "Detected public IP: ${IP:-<none — enter it manually>}"
echo

printf "Public host/IP clients reach this server at [%s]: " "$IP"; read -r HOST || HOST=""
[ -z "$HOST" ] && HOST="$IP"
printf "coturn external (public) IP [%s]: " "$HOST"; read -r EXTIP || EXTIP=""
[ -z "$EXTIP" ] && EXTIP="$HOST"
printf "Domain for automatic HTTPS (blank to skip the tls profile): "; read -r DOMAIN || DOMAIN=""
printf "Lock CORS to an origin (blank = allow any '*'): "; read -r ORIGIN || ORIGIN=""

umask 077
cat > "$ENV_FILE" <<EOF
# Generated by setup.sh — keep this file private (contains the TURN secret).
KEYWAVE_ALLOWED_ORIGINS=${ORIGIN:-*}
KEYWAVE_TURN_HOST=$HOST
KEYWAVE_TURN_SECRET=$SECRET
KEYWAVE_TURN_EXTERNAL_IP=$EXTIP
KEYWAVE_DOMAIN=$DOMAIN
EOF
chmod 600 "$ENV_FILE"

echo
echo "Wrote $ENV_FILE (chmod 600)."
echo
echo "Next steps:"
echo "  1. Open these ports on your firewall / cloud security group:"
echo "       UDP+TCP 3478   and   UDP 49160-49200      (TURN)"
[ -n "$DOMAIN" ] && echo "       TCP 80 + 443                            (HTTPS via Caddy)"
echo "  2. Start it:"
if [ -n "$DOMAIN" ]; then
  echo "       docker compose --profile turn --profile tls up -d --build"
  echo "     (point $DOMAIN's DNS at this host first; then open https://$DOMAIN)"
else
  echo "       docker compose --profile turn up -d --build"
  echo "     (serve it over HTTPS via your own reverse proxy -> http://keywave:5000)"
fi
echo "  3. Verify the relay started:"
echo "       docker logs keywave-turn | grep -i 'listener address'   # expect addresses, no errors"
echo "  4. Optional: prove TURN is used by adding KEYWAVE_FORCE_RELAY=1 to .env and recreating."
